# Generated by Django 4.1.3 on 2022-11-28 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flipkart", "0004_order_detl"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Order_detl",
            new_name="Order_details",
        ),
        migrations.RenameField(
            model_name="order_details",
            old_name="prouct",
            new_name="product",
        ),
    ]
